paths:
  /mockingproducts:
    get:
      summary: Obtener todos los productos
      description: Devuelve todos los productos en la base de datos.
      tags:
        - Products
      responses:
        "200":
          description: Los productos fueron devueltos correctamente
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#components/schemas/Product"
        "500":
          description: Error del servidor.
  /api/products/products/{pid}:
    get:
      summary: Obtener un producto por ID
      tags:
        - Products
      parameters:
        - name: pid
          in: path
          required: true
          decription: ID del producto que se busca
          schema:
            $type: String
      responses:
        "200":
          description: Producto encontrado
          content:
            application/json:
              schema:
                $ref: "#components/schemas/Product"
        "404":
          description: Producto no encontrado
        "500":
          description: Error en el servidor
  /api/products/mockingproducts:
    get:
      summary: Obtener una muestra autogenerada de productos creados con el modulo Faker
      tags:
        - Products
      description: Devuelve una muestra autogenerada de productos creados con Faker
      responses:
        "200":
          description: OK
          schema:
            type: array
            items:
              $ref: "#components/schemas/Product"
        "500":
          description: Error en el servidor
  /api/products:
    post:
      summary: Agregar un producto
      tags:
        - Products
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#components/requestBodies/ProductInput"
      responses:
        "200":
          description: Producto creado
          schema:
            $ref: "#components/schemas/Product"
        "500":
          description: Error en el servidor
        "401":
          description: No autorizado
  /api/products/{pid}:
    put:
      summary: Actualiza un producto desde su id
      description: Actualiza el producto que coincide con el ID suministrado en la base de datos.
      tags:
        - Products
      parameters:
        - name: pid
          in: path
          required: true
          decription: ID del producto a modificar
          schema:
            $type: String
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#components/requestBodies/ProductInput"
      responses:
        "200":
          description: Producto actualizado
          schema:
            $ref: "#components/schemas/Product"
        "404":
          description: Producto no encontrado
        "500":
          description: Error en el servidor
        "401":
          description: No autorizado
    delete:
      summary: Eliminar un producto
      tags:
        - Products
      description: Elimina el producto que coincide con el ID suministrado de la base de datos.
      parameters:
        - name: pid
          in: path
          description: ID del producto
          required: true
          type: string
      responses:
        "200":
          description: Producto eliminado con éxito
        "401":
          description: No autorizado
        "404":
          description: Producto no encontrado
        "500":
          description: Error en el servidor

components:
  schemas:
    Product:
      type: object
      properties:
        _id:
          type: ObjectId
          description: ID auto generado by mongo
        title:
          type: String
          description: Nombre del producto
        description:
          type: String
          description: Descripcion del producto
        price:
          type: Number
          description: Precio del producto
        thumbnails:
          type: Array
          description: Array de direcciones URL de las imagenes.
          items:
            type: String
        code:
          type: Number
          description: Código único identificador del producto.
        stock:
          type: Number
          description: Stock disponible del producto.
        category:
          type: String
          description: Categoria del producto
        status:
          type: Boolean
          description: Estado actual del producto
        owner:
          type: String
          description: Propietario del producto publicado en el catalogo. Corresponde al id de un usuario.
          example: admin
      example:
        _id: ObjectId("647376ee821c4c00fcca2eec")
        title: Cerveza honey
        description: Deliciosa cerveza rubia
        price: 19.99
        thumbnails:
          - https://www.google.com/url?sa=i&url=https%3A%2F%2Ffiumealmacengourmet.mitiendanube.com%2Fproductos%2Fcerveza-patagonia-bohemian-pilsener%2F&psig=AOvVaw0-XfJYnJv0AsHh5BVKlu1T&ust=1685387633756000&source=images&cd=vfe&ved=0CBEQjRxqFwoTCNiXrqzcmP8CFQAAAAAdAAAAABAE
        code: 589741
        stock: 1
        category: Bebidas alcoholicas
        status: true
        owner: admin
  requestBodies:
    ProductInput:
      type: object
      properties:
        title:
          type: String
          description: Nombre del producto
        description:
          type: String
          description: Descripcion del producto
        price:
          type: Number
          description: Precio del producto
        thumbnails:
          type: Array
          description: Array de direcciones URL de las imagenes.
          items:
            type: String
        code:
          type: Number
          description: Código único identificador del producto.
        stock:
          type: Number
          description: Stock disponible del producto.
        category:
          type: String
          description: Categoria del producto
        status:
          type: Boolean
          description: Estado actual del producto
        owner:
          type: String
          description: Propietario del producto publicado. Corresponde al id de un usuario.
          example: admin
      example:
        title: Teclado de notebook
        description: Para todo tipo de preparaciones
        price: 19.99
        thumbnails:
          - https://jpeg;base64,/9j/4AAQSkZJRgABAQAAAQABAAD/2wCEAAkGBwgHBgkIBwgKCgkLDRYPDQwMDRsUF
        code: 12345
        stock: 10
        category: Electronica
        status: true
        owner: admin
